#!/bin/sh
#SBATCH --time=12:00:00          # Run time in hh:mm:ss
#SBATCH --mem-per-cpu=8gb       # Minimum memory required per CPU (in megabytes)
#SBATCH --ntasks=6
#SBATCH --job-name=align
#SBATCH --error=coursen.err
#SBATCH --output=coursen.out
 
module load compiler/gcc openmpi

mpirun /Path/To/Dir/focus_assembler/bin/coarsen --workDir workDir --minDensity 5 --percentMerged .001 --verbose --time
