#!/bin/sh
#SBATCH --time=24:00:00          # Run time in hh:mm:ss
#SBATCH --mem-per-cpu=8000       # Minimum memory required per CPU (in megabytes)
#SBATCH --ntasks=5
#SBATCH --job-name=unCoarsen
#SBATCH --error=uncoarsen.err
#SBATCH --output=uncoarsen.out
 
module load compiler/gcc openmpi

mpirun /Path/To/Dir/focus_assembler/bin/unCoarsen --workDir workDir --time
